name: 📦 Check and Release WeChat

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      has_update: ${{ steps.version-check.outputs.has_update }}
      modified_time: ${{ steps.version-check.outputs.modified_time }}
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install uv
        uses: astral-sh/setup-uv@v2
        with:
          enable-cache: true

      - name: Install just
        uses: extractions/setup-just@v2

      - name: Install Python dependencies
        run: uv sync

      - name: Check for updates
        id: version-check
        run: just check

  release:
    needs: [check]
    if: needs.check.outputs.has_update == 'true'
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - uses: astral-sh/setup-uv@v2
        with:
          enable-cache: true

      - uses: extractions/setup-just@v2

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y p7zip-full

      - name: Install Python dependencies
        run: uv sync

      - name: Download and process WeChat
        id: process
        run: just process

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ steps.process.outputs.version }}
          name: WeChat ${{ steps.process.outputs.version }}
          body: ${{ steps.process.outputs.release_body }}
          artifacts: ${{ steps.process.outputs.file_path }}
          makeLatest: true
          allowUpdates: false
          skipIfReleaseExists: true
          token: ${{ secrets.GITHUB_TOKEN }}
